steps:
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  #args: ['up', '-d']
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/eshop::$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'eshoppublicapi:latest', 'gcr.io/$PROJECT_ID/eshop:$COMMIT_SHA']
  args: ["push", "gcr.io/$PROJECT_ID/eshoppublicapi"]
#images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']  
tags: ['cloud-builders-community']
